#import <DVTFoundation/CDStructures.h>
#import <DVTFoundation/DTDKAddAppIDService.h>
#import <DVTFoundation/DTDKAddApplicationGroupToTeamService.h>
#import <DVTFoundation/DTDKAddApplicationGroupsToAppIDService.h>
#import <DVTFoundation/DTDKAddCloudContainerToTeamService.h>
#import <DVTFoundation/DTDKAddCloudContainersToAppIDService.h>
#import <DVTFoundation/DTDKAddDeviceService.h>
#import <DVTFoundation/DTDKAddOMCIdentifierToTeamService.h>
#import <DVTFoundation/DTDKAddOMCIdentifiersToAppIDService.h>
#import <DVTFoundation/DTDKAddShoeboxIDService.h>
#import <DVTFoundation/DTDKCertificateAuthorityService.h>
#import <DVTFoundation/DTDKCertificateService.h>
#import <DVTFoundation/DTDKCreateProvisioningProfileService.h>
#import <DVTFoundation/DTDKDeleteAppIDService.h>
#import <DVTFoundation/DTDKDeleteProvisioningProfileService.h>
#import <DVTFoundation/DTDKDeleteShoeboxIDService.h>
#import <DVTFoundation/DTDKDeveloperInfoService.h>
#import <DVTFoundation/DTDKDeveloperPortalService.h>
#import <DVTFoundation/DTDKDownloadCertService.h>
#import <DVTFoundation/DTDKDownloadProvisioningProfileService.h>
#import <DVTFoundation/DTDKFetchAppIDService.h>
#import <DVTFoundation/DTDKListAppIDsService.h>
#import <DVTFoundation/DTDKListApplicationGroupsForTeamService.h>
#import <DVTFoundation/DTDKListCSRsService.h>
#import <DVTFoundation/DTDKListCertService.h>
#import <DVTFoundation/DTDKListCloudContainersForAppIDService.h>
#import <DVTFoundation/DTDKListCloudContainersForTeamService.h>
#import <DVTFoundation/DTDKListDeviceService.h>
#import <DVTFoundation/DTDKListEverythingService.h>
#import <DVTFoundation/DTDKListOMCIdentifiersForTeamService.h>
#import <DVTFoundation/DTDKListProvisioningProfileService.h>
#import <DVTFoundation/DTDKListShoeboxIDsService.h>
#import <DVTFoundation/DTDKListTeamService.h>
#import <DVTFoundation/DTDKRemoveDeviceService.h>
#import <DVTFoundation/DTDKRenameDeviceService.h>
#import <DVTFoundation/DTDKRenewProvisioningProfileService.h>
#import <DVTFoundation/DTDKRevokeCertService.h>
#import <DVTFoundation/DTDKServerCancelJoinTeamService.h>
#import <DVTFoundation/DTDKServerDownloadTeamClientCertificateService.h>
#import <DVTFoundation/DTDKServerDownloadTeamDevelopmentCertificateService.h>
#import <DVTFoundation/DTDKServerJoinTeamService.h>
#import <DVTFoundation/DTDKServerRenewTeamMembershipTeamService.h>
#import <DVTFoundation/DTDKServerRequestTeamDevelopmentCertificateService.h>
#import <DVTFoundation/DTDKServerRevokeTeamMembershipTeamService.h>
#import <DVTFoundation/DTDKSubmitCSRService.h>
#import <DVTFoundation/DTDKTeamBasedService.h>
#import <DVTFoundation/DTDKUpdateAppIDService.h>
#import <DVTFoundation/DTXAllowedRPC-Protocol.h>
#import <DVTFoundation/DVTAbstractMacDevice.h>
#import <DVTFoundation/DVTActivationRule.h>
#import <DVTFoundation/DVTAddAppIDOperation.h>
#import <DVTFoundation/DVTAddApplicationGroupToTeamOperation.h>
#import <DVTFoundation/DVTAddApplicationGroupsToAppIDOperation.h>
#import <DVTFoundation/DVTAddCloudContainerToTeamOperation.h>
#import <DVTFoundation/DVTAddCloudContainersToAppIDOperation.h>
#import <DVTFoundation/DVTAddDeviceOperation.h>
#import <DVTFoundation/DVTAddOMCIdentifierToTeamOperation.h>
#import <DVTFoundation/DVTAddOMCIdentifiersToAppIDOperation.h>
#import <DVTFoundation/DVTAppExtensionInstallPromiseManager.h>
#import <DVTFoundation/DVTAppIDFeatures.h>
#import <DVTFoundation/DVTAppIDRecord.h>
#import <DVTFoundation/DVTAppleIDBasedDeveloperAccount.h>
#import <DVTFoundation/DVTApplicationGroupRecord.h>
#import <DVTFoundation/DVTArchitecture.h>
#import <DVTFoundation/DVTArrayObservingBlockToken.h>
#import <DVTFoundation/DVTAssertingWeakInterposer_ProxyHelperReference.h>
#import <DVTFoundation/DVTAssertingWeakInterposer_RuntimeWeakReference.h>
#import <DVTFoundation/DVTAssertionHandler.h>
#import <DVTFoundation/DVTAssertionHandling-Protocol.h>
#import <DVTFoundation/DVTAutosynchingProxyArray.h>
#import <DVTFoundation/DVTBlockBasedCancellationToken.h>
#import <DVTFoundation/DVTBlockScanner.h>
#import <DVTFoundation/DVTBloomFilter.h>
#import <DVTFoundation/DVTBuildVersion.h>
#import <DVTFoundation/DVTByteBuffer.h>
#import <DVTFoundation/DVTCPlusPlusSourceModelParser.h>
#import <DVTFoundation/DVTCSourceModelParser.h>
#import <DVTFoundation/DVTCancellable-Protocol.h>
#import <DVTFoundation/DVTCancellationBlockCompletion-Protocol.h>
#import <DVTFoundation/DVTCertBasedDeveloperAccount.h>
#import <DVTFoundation/DVTCertificateRecord.h>
#import <DVTFoundation/DVTCertificateUtilities.h>
#import <DVTFoundation/DVTCharStream.h>
#import <DVTFoundation/DVTCheapReusableSubstring.h>
#import <DVTFoundation/DVTCloudContainerRecord.h>
#import <DVTFoundation/DVTCodesignParameterSnapshot.h>
#import <DVTFoundation/DVTCodesignResolver.h>
#import <DVTFoundation/DVTCodesignableDevice-Protocol.h>
#import <DVTFoundation/DVTCollectCertificateFailuresOperation.h>
#import <DVTFoundation/DVTCommandLineOptionDefinition.h>
#import <DVTFoundation/DVTCommandLineParser.h>
#import <DVTFoundation/DVTCommandLineTool.h>
#import <DVTFoundation/DVTComparisonDocumentLocation.h>
#import <DVTFoundation/DVTConcreteHashTable.h>
#import <DVTFoundation/DVTConcreteMapTable.h>
#import <DVTFoundation/DVTConcreteMapTableValueEnumerator.h>
#import <DVTFoundation/DVTConcretePointerArray.h>
#import <DVTFoundation/DVTConcretePointerFunctions.h>
#import <DVTFoundation/DVTConfinementService.h>
#import <DVTFoundation/DVTConfinementServiceConnection.h>
#import <DVTFoundation/DVTConsoleLogger.h>
#import <DVTFoundation/DVTConsoleOutputFileHandle.h>
#import <DVTFoundation/DVTCopyOnWriteMutableArray.h>
#import <DVTFoundation/DVTCreateProfileOperation.h>
#import <DVTFoundation/DVTCustomDataOwnership.h>
#import <DVTFoundation/DVTCustomDataSpecifier.h>
#import <DVTFoundation/DVTCustomDataStoring-Protocol.h>
#import <DVTFoundation/DVTDTApplicationWorkspaceClient-Protocol.h>
#import <DVTFoundation/DVTDeclaredPrimitiveFileDataType.h>
#import <DVTFoundation/DVTDelayedInvocation.h>
#import <DVTFoundation/DVTDelayedInvocationNew.h>
#import <DVTFoundation/DVTDeleteProfileOperation.h>
#import <DVTFoundation/DVTDeveloperAccount.h>
#import <DVTFoundation/DVTDeveloperAccountCredentials.h>
#import <DVTFoundation/DVTDeveloperAccountManager.h>
#import <DVTFoundation/DVTDeveloperAccountSession.h>
#import <DVTFoundation/DVTDeveloperInfoOperation.h>
#import <DVTFoundation/DVTDeveloperPaths.h>
#import <DVTFoundation/DVTDeveloperPortalDatabase.h>
#import <DVTFoundation/DVTDeveloperPortalResponseWrapper.h>
#import <DVTFoundation/DVTDeveloperPortalServiceConnection.h>
#import <DVTFoundation/DVTDeveloperProfile.h>
#import <DVTFoundation/DVTDeveloperProfileAccountProvider-Protocol.h>
#import <DVTFoundation/DVTDeveloperRecord.h>
#import <DVTFoundation/DVTDevice.h>
#import <DVTFoundation/DVTDeviceApplication-Protocol.h>
#import <DVTFoundation/DVTDeviceApplicationBase.h>
#import <DVTFoundation/DVTDeviceApplicationItem-Protocol.h>
#import <DVTFoundation/DVTDeviceApplicationProvider-Protocol.h>
#import <DVTFoundation/DVTDeviceCapability.h>
#import <DVTFoundation/DVTDeviceCapabilityMatchAnythingObject.h>
#import <DVTFoundation/DVTDeviceLocator.h>
#import <DVTFoundation/DVTDeviceManager.h>
#import <DVTFoundation/DVTDeviceRecord.h>
#import <DVTFoundation/DVTDeviceService.h>
#import <DVTFoundation/DVTDeviceSupportFiles.h>
#import <DVTFoundation/DVTDeviceType.h>
#import <DVTFoundation/DVTDiffBinaryDataSource.h>
#import <DVTFoundation/DVTDiffCharacterDataSource.h>
#import <DVTFoundation/DVTDiffContext.h>
#import <DVTFoundation/DVTDiffDataSource.h>
#import <DVTFoundation/DVTDiffDescriptor.h>
#import <DVTFoundation/DVTDiffHashing-Protocol.h>
#import <DVTFoundation/DVTDiffLineDataSource.h>
#import <DVTFoundation/DVTDiffWordDataSource.h>
#import <DVTFoundation/DVTDirectoryBasedCustomDataStore.h>
#import <DVTFoundation/DVTDirectoryBasedCustomDataStoreDelegate-Protocol.h>
#import <DVTFoundation/DVTDispatchLock.h>
#import <DVTFoundation/DVTDispatchLock_ReadWrite.h>
#import <DVTFoundation/DVTDispatchLock_Recursive.h>
#import <DVTFoundation/DVTDocumentFragmentFilter.h>
#import <DVTFoundation/DVTDocumentLocation.h>
#import <DVTFoundation/DVTDotSeparatedVersion.h>
#import <DVTFoundation/DVTDownloadCertificateOperation.h>
#import <DVTFoundation/DVTDownloadDeveloperIDCertificateAuthorityOperation.h>
#import <DVTFoundation/DVTDownloadProfileOperation.h>
#import <DVTFoundation/DVTDownloadTeamProfileOperation.h>
#import <DVTFoundation/DVTDownloadWWDRCertificateAuthorityOperation.h>
#import <DVTFoundation/DVTDownloadable.h>
#import <DVTFoundation/DVTDownloadableDependency.h>
#import <DVTFoundation/DVTDownloadableIndex.h>
#import <DVTFoundation/DVTDownloadableInstallationHelper-Protocol.h>
#import <DVTFoundation/DVTDownloadableManager.h>
#import <DVTFoundation/DVTDownloadableManagerIOCache.h>
#import <DVTFoundation/DVTDownloadableOperation.h>
#import <DVTFoundation/DVTDownloadableOperationDownload.h>
#import <DVTFoundation/DVTDownloadableOperationRefreshIndex.h>
#import <DVTFoundation/DVTDownloadableProgressToken.h>
#import <DVTFoundation/DVTDownloadable_PKInstallClientDelegate.h>
#import <DVTFoundation/DVTDynamicLogController.h>
#import <DVTFoundation/DVTDynamicPrimitiveFileDataType.h>
#import <DVTFoundation/DVTEncodableIndex.h>
#import <DVTFoundation/DVTEncodableIndexDelegate-Protocol.h>
#import <DVTFoundation/DVTEncodableIndexEntry.h>
#import <DVTFoundation/DVTExtendedPlatformInfo.h>
#import <DVTFoundation/DVTExtension.h>
#import <DVTFoundation/DVTExtensionAttributeDescription.h>
#import <DVTFoundation/DVTExtensionElementDescription.h>
#import <DVTFoundation/DVTExtensionParameter.h>
#import <DVTFoundation/DVTExtensionPoint.h>
#import <DVTFoundation/DVTExtensionPropertyDescription.h>
#import <DVTFoundation/DVTExtraXMLArchiveData.h>
#import <DVTFoundation/DVTExtraXMLAttribute.h>
#import <DVTFoundation/DVTExtraXMLElement.h>
#import <DVTFoundation/DVTFetchOrCreateAppIDOperation.h>
#import <DVTFoundation/DVTFileDataType.h>
#import <DVTFoundation/DVTFileDataTypeDetection.h>
#import <DVTFoundation/DVTFileDataTypeDetectionMagicCache.h>
#import <DVTFoundation/DVTFileDataTypeDetector-Protocol.h>
#import <DVTFoundation/DVTFileLogger.h>
#import <DVTFoundation/DVTFilePath.h>
#import <DVTFoundation/DVTFilePathEventWatcher.h>
#import <DVTFoundation/DVTFileSystemRepresentationProviding-Protocol.h>
#import <DVTFoundation/DVTFileSystemVNode.h>
#import <DVTFoundation/DVTFileWrapper.h>
#import <DVTFoundation/DVTFindDescriptor.h>
#import <DVTFoundation/DVTFindRegularExpressionDescriptor.h>
#import <DVTFoundation/DVTFindRegularExpressionResult.h>
#import <DVTFoundation/DVTFindResult.h>
#import <DVTFoundation/DVTFindTextualDescriptor.h>
#import <DVTFoundation/DVTFirstLaunchPackage.h>
#import <DVTFoundation/DVTFirstLaunchPackageInstallationHelper.h>
#import <DVTFoundation/DVTFoundation.h>
#import <DVTFoundation/DVTFuture.h>
#import <DVTFoundation/DVTGeneratedContentProvider.h>
#import <DVTFoundation/DVTGlobalCustomDataStore.h>
#import <DVTFoundation/DVTHTMLEntityScanner.h>
#import <DVTFoundation/DVTHTMLScanner.h>
#import <DVTFoundation/DVTHashTable.h>
#import <DVTFoundation/DVTInvalidExtension.h>
#import <DVTFoundation/DVTInvalidation-Protocol.h>
#import <DVTFoundation/DVTInvalidationMixIn.h>
#import <DVTFoundation/DVTKVCMethodStyle.h>
#import <DVTFoundation/DVTKVOConditionValidator.h>
#import <DVTFoundation/DVTKeywordScanner.h>
#import <DVTFoundation/DVTKnownStringMapping.h>
#import <DVTFoundation/DVTLanguageSpecification.h>
#import <DVTFoundation/DVTLibraryFragmentFilter.h>
#import <DVTFoundation/DVTLicenseAgreementHelper.h>
#import <DVTFoundation/DVTListAppIDsOperation.h>
#import <DVTFoundation/DVTListApplicationGroupsForTeamOperation.h>
#import <DVTFoundation/DVTListCertsOperation.h>
#import <DVTFoundation/DVTListCloudContainersForAppIDOperation.h>
#import <DVTFoundation/DVTListCloudContainersForTeamOperation.h>
#import <DVTFoundation/DVTListDevicesOperation.h>
#import <DVTFoundation/DVTListEverythingOperation.h>
#import <DVTFoundation/DVTListOMCIdentifiersForTeamOperation.h>
#import <DVTFoundation/DVTListProvisioningProfilesOperation.h>
#import <DVTFoundation/DVTListShoeboxIDsOperation.h>
#import <DVTFoundation/DVTListTeamOperation.h>
#import <DVTFoundation/DVTLocalComputer.h>
#import <DVTFoundation/DVTLocalComputerLocator.h>
#import <DVTFoundation/DVTLocalProcessInformation.h>
#import <DVTFoundation/DVTLocale.h>
#import <DVTFoundation/DVTLogAspect.h>
#import <DVTFoundation/DVTLogger.h>
#import <DVTFoundation/DVTMTReport.h>
#import <DVTFoundation/DVTMacroAssignmentInfo.h>
#import <DVTFoundation/DVTMacroDefinitionCondition.h>
#import <DVTFoundation/DVTMacroDefinitionConditionParameter.h>
#import <DVTFoundation/DVTMacroDefinitionConditionSet.h>
#import <DVTFoundation/DVTMacroDefinitionTable.h>
#import <DVTFoundation/DVTMacroExpansion-Protocol.h>
#import <DVTFoundation/DVTMacroExpansionBlock.h>
#import <DVTFoundation/DVTMacroExpansionIntegerMetric.h>
#import <DVTFoundation/DVTMacroExpansionOperator.h>
#import <DVTFoundation/DVTMacroExpansionReplacementOperator.h>
#import <DVTFoundation/DVTMacroExpansionReplacementOperatorWithParseError.h>
#import <DVTFoundation/DVTMacroExpansionReplacementOperator_base.h>
#import <DVTFoundation/DVTMacroExpansionReplacementOperator_dir.h>
#import <DVTFoundation/DVTMacroExpansionReplacementOperator_file.h>
#import <DVTFoundation/DVTMacroExpansionReplacementOperator_suffix.h>
#import <DVTFoundation/DVTMacroExpansionRetrievalOperator.h>
#import <DVTFoundation/DVTMacroExpansionRetrievalOperatorWithParseError.h>
#import <DVTFoundation/DVTMacroExpansionRetrievalOperator_base.h>
#import <DVTFoundation/DVTMacroExpansionRetrievalOperator_c99extidentifier.h>
#import <DVTFoundation/DVTMacroExpansionRetrievalOperator_dir.h>
#import <DVTFoundation/DVTMacroExpansionRetrievalOperator_file.h>
#import <DVTFoundation/DVTMacroExpansionRetrievalOperator_identifier.h>
#import <DVTFoundation/DVTMacroExpansionRetrievalOperator_lower.h>
#import <DVTFoundation/DVTMacroExpansionRetrievalOperator_quote.h>
#import <DVTFoundation/DVTMacroExpansionRetrievalOperator_rfc1034identifier.h>
#import <DVTFoundation/DVTMacroExpansionRetrievalOperator_standardizepath.h>
#import <DVTFoundation/DVTMacroExpansionRetrievalOperator_suffix.h>
#import <DVTFoundation/DVTMacroExpansionRetrievalOperator_upper.h>
#import <DVTFoundation/DVTMacroExpansionScope.h>
#import <DVTFoundation/DVTMacroExpansionStatistics.h>
#import <DVTFoundation/DVTMacroExpansionString.h>
#import <DVTFoundation/DVTMacroExpansionStringList.h>
#import <DVTFoundation/DVTMacroExpansionStringList_Literal.h>
#import <DVTFoundation/DVTMacroExpansionStringList_NonLiteral.h>
#import <DVTFoundation/DVTMacroExpansionString_Concatenation.h>
#import <DVTFoundation/DVTMacroExpansionString_Literal.h>
#import <DVTFoundation/DVTMacroExpansionString_StringSubstitution.h>
#import <DVTFoundation/DVTMacroExpansionString_Substitution.h>
#import <DVTFoundation/DVTMacroNameRegistry.h>
#import <DVTFoundation/DVTMacroNameRegistryRegistration.h>
#import <DVTFoundation/DVTMacroNameString.h>
#import <DVTFoundation/DVTMapTable.h>
#import <DVTFoundation/DVTMemorySnapshot.h>
#import <DVTFoundation/DVTMessageTrace.h>
#import <DVTFoundation/DVTMixIn.h>
#import <DVTFoundation/DVTMockDeveloperAccount.h>
#import <DVTFoundation/DVTMockProvisioningProfile.h>
#import <DVTFoundation/DVTMockProvisioningProfileManager.h>
#import <DVTFoundation/DVTMockSigningCertificate.h>
#import <DVTFoundation/DVTMockSigningCertificateSource.h>
#import <DVTFoundation/DVTModelObject-Protocol.h>
#import <DVTFoundation/DVTModelObject.h>
#import <DVTFoundation/DVTModelObjectGraph.h>
#import <DVTFoundation/DVTModelTree.h>
#import <DVTFoundation/DVTModelTreeNode.h>
#import <DVTFoundation/DVTMountedFileSystem.h>
#import <DVTFoundation/DVTMutableKnownStringSet.h>
#import <DVTFoundation/DVTMutableOrderedDictionary.h>
#import <DVTFoundation/DVTMutableOrderedSet.h>
#import <DVTFoundation/DVTMutableRangeArray.h>
#import <DVTFoundation/DVTNotificationToken.h>
#import <DVTFoundation/DVTNumberScanner.h>
#import <DVTFoundation/DVTOMCRecord.h>
#import <DVTFoundation/DVTOSVersion.h>
#import <DVTFoundation/DVTObjCPlusPlusSourceModelParser.h>
#import <DVTFoundation/DVTObjCSourceModelParser.h>
#import <DVTFoundation/DVTObjectDeallocationMonitor.h>
#import <DVTFoundation/DVTObservableObjectProxy.h>
#import <DVTFoundation/DVTObserveXPCServicesProtocol-Protocol.h>
#import <DVTFoundation/DVTObserveXPCServicesProtocol_Callback-Protocol.h>
#import <DVTFoundation/DVTObservingBlockToken.h>
#import <DVTFoundation/DVTObservingToken.h>
#import <DVTFoundation/DVTObsoleteUnarchivedObjectPlaceholder.h>
#import <DVTFoundation/DVTOneShotBlock.h>
#import <DVTFoundation/DVTOperation.h>
#import <DVTFoundation/DVTOperationGroup.h>
#import <DVTFoundation/DVTPatienceDiffContext.h>
#import <DVTFoundation/DVTPerformanceCheckpoint.h>
#import <DVTFoundation/DVTPerformanceMetric.h>
#import <DVTFoundation/DVTPerformanceStatistic.h>
#import <DVTFoundation/DVTPerformanceTestLogger_TimeForWork.h>
#import <DVTFoundation/DVTPerformanceTestOutput.h>
#import <DVTFoundation/DVTPerformanceTestParser-Protocol.h>
#import <DVTFoundation/DVTPerformanceTestResult.h>
#import <DVTFoundation/DVTPinger.h>
#import <DVTFoundation/DVTPipe.h>
#import <DVTFoundation/DVTPlatform.h>
#import <DVTFoundation/DVTPlatformFamily.h>
#import <DVTFoundation/DVTPlugIn.h>
#import <DVTFoundation/DVTPlugInLocalizedString.h>
#import <DVTFoundation/DVTPlugInLocator.h>
#import <DVTFoundation/DVTPlugInManager.h>
#import <DVTFoundation/DVTPlugInScanRecord.h>
#import <DVTFoundation/DVTPointerArray.h>
#import <DVTFoundation/DVTPointerFunctions.h>
#import <DVTFoundation/DVTPortalInfoOperation.h>
#import <DVTFoundation/DVTPortalOperation.h>
#import <DVTFoundation/DVTPortalOperationToken.h>
#import <DVTFoundation/DVTPrimitiveFileDataType.h>
#import <DVTFoundation/DVTProcessInformation.h>
#import <DVTFoundation/DVTProgressReporting-Protocol.h>
#import <DVTFoundation/DVTPromise-Protocol.h>
#import <DVTFoundation/DVTPropertyListEncoding-Protocol.h>
#import <DVTFoundation/DVTProvisioningProfile-Protocol.h>
#import <DVTFoundation/DVTProvisioningProfileManager.h>
#import <DVTFoundation/DVTProvisioningProfileProvider.h>
#import <DVTFoundation/DVTProvisioningProfileRecord.h>
#import <DVTFoundation/DVTPythonScanner.h>
#import <DVTFoundation/DVTRangeArray.h>
#import <DVTFoundation/DVTReferenceResolutionStrategy.h>
#import <DVTFoundation/DVTReferenceResolver.h>
#import <DVTFoundation/DVTReferenceResolverClient-Protocol.h>
#import <DVTFoundation/DVTRegExScanner.h>
#import <DVTFoundation/DVTRegexCommandLineOptionDefinition.h>
#import <DVTFoundation/DVTRegistrable-Protocol.h>
#import <DVTFoundation/DVTRegistry.h>
#import <DVTFoundation/DVTRegularExpression.h>
#import <DVTFoundation/DVTRegularExpressionMatch.h>
#import <DVTFoundation/DVTRelativeDateFormatting.h>
#import <DVTFoundation/DVTRescindCallbackObservingToken.h>
#import <DVTFoundation/DVTRevokeCertificateOperation.h>
#import <DVTFoundation/DVTRoleRecord.h>
#import <DVTFoundation/DVTRuleScanner.h>
#import <DVTFoundation/DVTSDK.h>
#import <DVTFoundation/DVTScannerRule.h>
#import <DVTFoundation/DVTSearchPath.h>
#import <DVTFoundation/DVTSelectorBasedObservingToken.h>
#import <DVTFoundation/DVTSelfInstrumentationSession-Protocol.h>
#import <DVTFoundation/DVTSemaphore.h>
#import <DVTFoundation/DVTServerCancelJoinTeamOperation.h>
#import <DVTFoundation/DVTServerDownloadTeamClientCertificateOperation.h>
#import <DVTFoundation/DVTServerDownloadTeamDevelopmentCertificateOperation.h>
#import <DVTFoundation/DVTServerJoinTeamOperation.h>
#import <DVTFoundation/DVTServerRenewTeamMembershipTeamOperation.h>
#import <DVTFoundation/DVTServerRequestTeamDevelopmentCertificateOperation.h>
#import <DVTFoundation/DVTServerRevokeTeamMembershipTeamOperation.h>
#import <DVTFoundation/DVTSharedObserver.h>
#import <DVTFoundation/DVTShoeboxIDRecord.h>
#import <DVTFoundation/DVTSigningCertificate.h>
#import <DVTFoundation/DVTSigningCertificateManager.h>
#import <DVTFoundation/DVTSigningCertificateSource.h>
#import <DVTFoundation/DVTSigningCertificateSourceDelegate-Protocol.h>
#import <DVTFoundation/DVTSigningIdentitySnapshot.h>
#import <DVTFoundation/DVTSimpleDeserializer.h>
#import <DVTFoundation/DVTSimplePlainTextDeserializer.h>
#import <DVTFoundation/DVTSimplePlainTextSerializer.h>
#import <DVTFoundation/DVTSimpleSerialization-Protocol.h>
#import <DVTFoundation/DVTSimpleSerializer.h>
#import <DVTFoundation/DVTSimpleXMLWriter.h>
#import <DVTFoundation/DVTSourceCodeLanguage.h>
#import <DVTFoundation/DVTSourceCodeSymbolKind.h>
#import <DVTFoundation/DVTSourceModel.h>
#import <DVTFoundation/DVTSourceModelItem.h>
#import <DVTFoundation/DVTSourceModelParser.h>
#import <DVTFoundation/DVTSourceModelParserInteriorProductionRule.h>
#import <DVTFoundation/DVTSourceModelParserProductionRule.h>
#import <DVTFoundation/DVTSourceModelParserProductionState.h>
#import <DVTFoundation/DVTSourceNodeTypes.h>
#import <DVTFoundation/DVTSourceScanner.h>
#import <DVTFoundation/DVTSourceSpecification.h>
#import <DVTFoundation/DVTSourceTokens.h>
#import <DVTFoundation/DVTSpecificApplicationProvider-Protocol.h>
#import <DVTFoundation/DVTStackBacktrace.h>
#import <DVTFoundation/DVTStackBacktraceFrame.h>
#import <DVTFoundation/DVTStateRepository.h>
#import <DVTFoundation/DVTStateToken.h>
#import <DVTFoundation/DVTStringBuffer.h>
#import <DVTFoundation/DVTStringRepresentationPersistable-Protocol.h>
#import <DVTFoundation/DVTSyntaxTypeSpecification.h>
#import <DVTFoundation/DVTSynthesizedFileDataType.h>
#import <DVTFoundation/DVTSysmonBridge.h>
#import <DVTFoundation/DVTSysmonBridgeDelegate-Protocol.h>
#import <DVTFoundation/DVTSystemActivityToken.h>
#import <DVTFoundation/DVTSystemEvents.h>
#import <DVTFoundation/DVTSystemStatisticsMeasurement.h>
#import <DVTFoundation/DVTTarjanSCCVertex.h>
#import <DVTFoundation/DVTTask.h>
#import <DVTFoundation/DVTTeamOperationBase.h>
#import <DVTFoundation/DVTTeamRecord.h>
#import <DVTFoundation/DVTTestPerformanceMetricOutput.h>
#import <DVTFoundation/DVTTextDocumentLocation.h>
#import <DVTFoundation/DVTTextFinder.h>
#import <DVTFoundation/DVTTextFindable-Protocol.h>
#import <DVTFoundation/DVTTextPreferences.h>
#import <DVTFoundation/DVTTextReplacable-Protocol.h>
#import <DVTFoundation/DVTTextlikeFindDescriptor-Protocol.h>
#import <DVTFoundation/DVTToolchain.h>
#import <DVTFoundation/DVTToolchainRegistry.h>
#import <DVTFoundation/DVTToolsInfo.h>
#import <DVTFoundation/DVTToolsVersion.h>
#import <DVTFoundation/DVTUnknownPrimitiveFileDataType.h>
#import <DVTFoundation/DVTUpdateAppIDOperation.h>
#import <DVTFoundation/DVTUpdatePortalDatabaseOperation.h>
#import <DVTFoundation/DVTUpdateProfileOperation.h>
#import <DVTFoundation/DVTUserNotificationCenter.h>
#import <DVTFoundation/DVTVersion.h>
#import <DVTFoundation/DVTWeakCallBack.h>
#import <DVTFoundation/DVTWeakInterposer.h>
#import <DVTFoundation/DVTWeakInterposer_ProxyHelperReference.h>
#import <DVTFoundation/DVTWeakInterposer_RuntimeWeakReference.h>
#import <DVTFoundation/DVTWeakReference.h>
#import <DVTFoundation/DVTXMLArchiver.h>
#import <DVTFoundation/DVTXMLUnarchiver.h>
#import <DVTFoundation/DVTXMLUnarchiverDelegate-Protocol.h>
#import <DVTFoundation/DVTXMLUnarchiving-Protocol.h>
#import <DVTFoundation/DVTXPCServiceInformation.h>
#import <DVTFoundation/DVTXPCServiceObserver.h>
#import <DVTFoundation/DataGatheringNSURLConnectionDelegate.h>
#import <DVTFoundation/DataWritingNSURLConnectionDelegate.h>
#import <DVTFoundation/NSArray-DVTDiffHashing.h>
#import <DVTFoundation/NSArray-DVTFoundationClassAdditions.h>
#import <DVTFoundation/NSArray-DVTMacroExpansion.h>
#import <DVTFoundation/NSArray-DVTMacroExpansionAdditions.h>
#import <DVTFoundation/NSArray-DVTObservingConvenience.h>
#import <DVTFoundation/NSArray-DVTRangeArrayAdditions.h>
#import <DVTFoundation/NSArray-DVTShellUtilitiesAdditions.h>
#import <DVTFoundation/NSBlockOperation-DVTNSOperationAdditions.h>
#import <DVTFoundation/NSBundle-DVTNSBundleAdditions.h>
#import <DVTFoundation/NSCharacterSet-DVTFoundationClassAdditions.h>
#import <DVTFoundation/NSCoding-Protocol.h>
#import <DVTFoundation/NSCopying-Protocol.h>
#import <DVTFoundation/NSData-DVTDiffHashing.h>
#import <DVTFoundation/NSData-DVTFoundationClassAdditions.h>
#import <DVTFoundation/NSData-DVTNSDataStdIO.h>
#import <DVTFoundation/NSData-DVTSecurityAdditions.h>
#import <DVTFoundation/NSDate-DVTFoundationClassAdditions.h>
#import <DVTFoundation/NSDictionary-ADCDownloadAuthenticationResponse.h>
#import <DVTFoundation/NSDictionary-DVTDiffHashing.h>
#import <DVTFoundation/NSDictionary-DVTFoundationClassAdditions.h>
#import <DVTFoundation/NSDictionary-DVTMacroExpansionAdditions.h>
#import <DVTFoundation/NSDistributedNotificationCenter-DVTNSNotificationCenterAdditions.h>
#import <DVTFoundation/NSError-DVTFoundationClassAdditions.h>
#import <DVTFoundation/NSError-DVTSecurityAdditions.h>
#import <DVTFoundation/NSFastEnumeration-Protocol.h>
#import <DVTFoundation/NSFileHandle-DVTNSFileHandleAdditions.h>
#import <DVTFoundation/NSFileHandle-DVTTaskAdditions.h>
#import <DVTFoundation/NSFileManager-DVTNSFileManagerAdditions.h>
#import <DVTFoundation/NSHTTPURLResponse-DVTHTTPCookies.h>
#import <DVTFoundation/NSInputStream-DVTFoundationClassAdditions.h>
#import <DVTFoundation/NSKeyedUnarchiverDelegate-Protocol.h>
#import <DVTFoundation/NSLock-DVTFoundationExtensions.h>
#import <DVTFoundation/NSMapTable-DVTNSMapTableAdditions.h>
#import <DVTFoundation/NSMutableArray-DVTFoundationClassAdditions.h>
#import <DVTFoundation/NSMutableCopying-Protocol.h>
#import <DVTFoundation/NSMutableData-DVTFoundationClassAdditions.h>
#import <DVTFoundation/NSMutableData-DVTNSDataStdIO.h>
#import <DVTFoundation/NSMutableDictionary-DVTFoundationClassAdditions.h>
#import <DVTFoundation/NSMutableSet-DVTNSMutableSetAdditions.h>
#import <DVTFoundation/NSMutableString-DVTFoundationClassAdditions.h>
#import <DVTFoundation/NSMutableURLRequest-DVTHTTPCookies.h>
#import <DVTFoundation/NSNotificationCenter-DVTNSNotificationCenterAdditions.h>
#import <DVTFoundation/NSNumber-DVTDiffHashing.h>
#import <DVTFoundation/NSObject-DVTArcSupport.h>
#import <DVTFoundation/NSObject-DVTAssertionSupport.h>
#import <DVTFoundation/NSObject-DVTExtraXMArchiveDataAdditions.h>
#import <DVTFoundation/NSObject-DVTInvalidation.h>
#import <DVTFoundation/NSObject-DVTInvalidation2.h>
#import <DVTFoundation/NSObject-DVTInvalidation2Private.h>
#import <DVTFoundation/NSObject-DVTKVCMutableCollectionPropertySupport.h>
#import <DVTFoundation/NSObject-DVTKVOAssertionValidationMethods.h>
#import <DVTFoundation/NSObject-DVTNSRunLoopAdditions.h>
#import <DVTFoundation/NSObject-DVTObjectDeallocationMonitorAdditions.h>
#import <DVTFoundation/NSObject-DVTObservingConvenience.h>
#import <DVTFoundation/NSObject-DVTPropertyLinking.h>
#import <DVTFoundation/NSObject-DVTSelectorAdditions.h>
#import <DVTFoundation/NSObject-DVTSharedObserverAccess.h>
#import <DVTFoundation/NSObject-DVTSimpleSerialization.h>
#import <DVTFoundation/NSObject-DVTXMLArchiving.h>
#import <DVTFoundation/NSObject-DVTXMLUnarchivingPartial.h>
#import <DVTFoundation/NSObject-Deprecated.h>
#import <DVTFoundation/NSOutputStream-DVTFoundationClassAdditions.h>
#import <DVTFoundation/NSProcessInfo-DVTNSProcessInfoAdditions.h>
#import <DVTFoundation/NSProcessInfo-DVTNSProcessInfoCachedEnvironmentAdditions.h>
#import <DVTFoundation/NSPropertyListSerialization-DVTNSPropertyListSerializationAdditions.h>
#import <DVTFoundation/NSRecursiveLock-DVTFoundationExtensions.h>
#import <DVTFoundation/NSRunLoop-DVTNSRunLoopAdditions.h>
#import <DVTFoundation/NSSecureCoding-Protocol.h>
#import <DVTFoundation/NSSet-DVTNSSetAdditions.h>
#import <DVTFoundation/NSString-DVTDiffHashing.h>
#import <DVTFoundation/NSString-DVTFileSystemRepresentationProviding.h>
#import <DVTFoundation/NSString-DVTFoundationANSIText.h>
#import <DVTFoundation/NSString-DVTFoundationClassAdditions.h>
#import <DVTFoundation/NSString-DVTMacroDefinitionAdditions.h>
#import <DVTFoundation/NSString-DVTMacroExpansion.h>
#import <DVTFoundation/NSString-DVTMacroExpansionAdditions.h>
#import <DVTFoundation/NSString-DVTMacroNameStringCompatibility.h>
#import <DVTFoundation/NSThread-DVTObjectAllocationTracking.h>
#import <DVTFoundation/NSURL-DVTNSURLAdditions.h>
#import <DVTFoundation/NSURL-DVTSecurityAdditions.h>
#import <DVTFoundation/NSURLConnectionDataDelegate-Protocol.h>
#import <DVTFoundation/NSURLConnectionDelegate-Protocol.h>
#import <DVTFoundation/NSURLProtectionSpace-DVTSecurityAdditions.h>
#import <DVTFoundation/NSUserDefaults-DVTNSUserDefaultsAdditions.h>
#import <DVTFoundation/NSUserNotificationCenterDelegate-Protocol.h>
#import <DVTFoundation/NSValue-DVTGeometryAdditions.h>
#import <DVTFoundation/NSXMLElement-DVTFoundationClassAdditions.h>
#import <DVTFoundation/_DVTAsynchronousRequest.h>
#import <DVTFoundation/_DVTCancellationBlockToken.h>
#import <DVTFoundation/_DVTDeallocationMonitorInfo.h>
#import <DVTFoundation/_DVTDeviceLocatorTracker.h>
#import <DVTFoundation/_DVTDiffHashingDictionaryDiffHashContext.h>
#import <DVTFoundation/_DVTDiffLineDataSourceConsistentCopy.h>
#import <DVTFoundation/_DVTDisallowFinishToken.h>
#import <DVTFoundation/_DVTErrorRecoveryHandler.h>
#import <DVTFoundation/_DVTFilePathAssoc.h>
#import <DVTFoundation/_DVTFoundationPrivateClassForFindingBundle.h>
#import <DVTFoundation/_DVTLogObjectsRequest.h>
#import <DVTFoundation/_DVTNotificationReceiver.h>
#import <DVTFoundation/_DVTWeakInterposerHelper.h>
#import <DVTFoundation/_DVTXMLParsingState.h>
