#import <IDEFoundation/DTXAllowedRPC-Protocol.h>
#import <IDEFoundation/DVTAbstractMacDevice-IDEFoundationAdditions.h>
#import <IDEFoundation/DVTCancellable-Protocol.h>
#import <IDEFoundation/DVTCustomDataStoring-Protocol.h>
#import <IDEFoundation/DVTDeveloperProfileAccountProvider-Protocol.h>
#import <IDEFoundation/DVTDevice-IDEFoundationAdditions.h>
#import <IDEFoundation/DVTDocumentLocation-IDEActivityLogMessageAdditions.h>
#import <IDEFoundation/DVTDocumentLocation-IDEFoundationAdditions.h>
#import <IDEFoundation/DVTExtension-DVTExtensionSortAdditions.h>
#import <IDEFoundation/DVTExtension-DVTExtensionTypeIdentificationUtilities.h>
#import <IDEFoundation/DVTFilePath-IDESourceControlPatchAdditions.h>
#import <IDEFoundation/DVTFilePath-IDESourceControlStatus.h>
#import <IDEFoundation/DVTFilePath-IDESourceControlStatus_Private.h>
#import <IDEFoundation/DVTFilePath-IDESourceControlUtilities.h>
#import <IDEFoundation/DVTFilePath-PersistenceFSEventsMonitoring.h>
#import <IDEFoundation/DVTInvalidation-Protocol.h>
#import <IDEFoundation/DVTLocalComputer-IDEFoundationAdditions.h>
#import <IDEFoundation/DVTPerformanceTestParser-Protocol.h>
#import <IDEFoundation/DVTPlatform-IDEExtendedPlatformInfo.h>
#import <IDEFoundation/DVTProgressReporting-Protocol.h>
#import <IDEFoundation/DVTSimpleSerialization-Protocol.h>
#import <IDEFoundation/DVTSourceControlManager-IDESourceControlManager.h>
#import <IDEFoundation/DVTSourceControlSystem-IDESourceControlSystem.h>
#import <IDEFoundation/DVTSourceControlWorkspace-IDEFoundationClassAdditions.h>
#import <IDEFoundation/DVTSourceControlWorkspaceBlueprint-IDEFoundationClassAdditions.h>
#import <IDEFoundation/DVTTask-IDEDistributionProcessingPipelineTasks.h>
#import <IDEFoundation/DVTTextDocumentLocation-IDEActivityLogMessageAdditions.h>
#import <IDEFoundation/DVTToolsInfo-IDEDVTToolsInfoAdditions.h>
#import <IDEFoundation/DVTXMLUnarchiving-Protocol.h>
#import <IDEFoundation/IDEActivityLogActionMessage.h>
#import <IDEFoundation/IDEActivityLogAddSubmessageChangeEvent.h>
#import <IDEFoundation/IDEActivityLogAddSubsectionChangeEvent.h>
#import <IDEFoundation/IDEActivityLogAnalyzerControlFlowStepEdge.h>
#import <IDEFoundation/IDEActivityLogAnalyzerControlFlowStepMessage.h>
#import <IDEFoundation/IDEActivityLogAnalyzerEventStepMessage.h>
#import <IDEFoundation/IDEActivityLogAnalyzerResultMessage.h>
#import <IDEFoundation/IDEActivityLogAnalyzerStepMessage.h>
#import <IDEFoundation/IDEActivityLogAnalyzerWarningMessage.h>
#import <IDEFoundation/IDEActivityLogAppendTextChangeEvent.h>
#import <IDEFoundation/IDEActivityLogChangeEvent.h>
#import <IDEFoundation/IDEActivityLogContextInfoMessage.h>
#import <IDEFoundation/IDEActivityLogHeaderInclusionMessage.h>
#import <IDEFoundation/IDEActivityLogMessage.h>
#import <IDEFoundation/IDEActivityLogRecord.h>
#import <IDEFoundation/IDEActivityLogSection.h>
#import <IDEFoundation/IDEActivityLogSectionObservation.h>
#import <IDEFoundation/IDEActivityLogSectionRecorder.h>
#import <IDEFoundation/IDEActivityLogSetKeyValueChangeEvent.h>
#import <IDEFoundation/IDEActivityLogStopRecordingChangeEvent.h>
#import <IDEFoundation/IDEActivityLogUnitTestSection.h>
#import <IDEFoundation/IDEActivityLogUnitTestSectionRecorder.h>
#import <IDEFoundation/IDEAddressBreakpoint.h>
#import <IDEFoundation/IDEAlert.h>
#import <IDEFoundation/IDEAlertEvent.h>
#import <IDEFoundation/IDEAnalysisTool.h>
#import <IDEFoundation/IDEAnalyzeCommandLineVerb.h>
#import <IDEFoundation/IDEAnalyzeSchemeAction.h>
#import <IDEFoundation/IDEAppClientTracker.h>
#import <IDEFoundation/IDEAppleScriptBreakpointAction.h>
#import <IDEFoundation/IDEArchive.h>
#import <IDEFoundation/IDEArchiveCommandLineVerb.h>
#import <IDEFoundation/IDEArchiveIdentityFilter.h>
#import <IDEFoundation/IDEArchiveManager.h>
#import <IDEFoundation/IDEArchivePackager.h>
#import <IDEFoundation/IDEArchivePackagerEntitlementsMerger.h>
#import <IDEFoundation/IDEArchivePathsSnapshot.h>
#import <IDEFoundation/IDEArchiveProcessingOperation.h>
#import <IDEFoundation/IDEArchiveSchemeAction.h>
#import <IDEFoundation/IDEArchivedApplication.h>
#import <IDEFoundation/IDEArchivedContent.h>
#import <IDEFoundation/IDEArchivedInAppContent.h>
#import <IDEFoundation/IDEArchivingOperation.h>
#import <IDEFoundation/IDEArchivingOperationGroup.h>
#import <IDEFoundation/IDEAutoImportable-Protocol.h>
#import <IDEFoundation/IDEBatchFindHistoryItem.h>
#import <IDEFoundation/IDEBatchFindManager.h>
#import <IDEFoundation/IDEBlueprint-Protocol.h>
#import <IDEFoundation/IDEBlueprintProvider-Protocol.h>
#import <IDEFoundation/IDEBotSCMAction.h>
#import <IDEFoundation/IDEBreakpoint.h>
#import <IDEFoundation/IDEBreakpointAction.h>
#import <IDEFoundation/IDEBreakpointActionArchivingProxy.h>
#import <IDEFoundation/IDEBreakpointActionEvaluationContext.h>
#import <IDEFoundation/IDEBreakpointArchivingProxy.h>
#import <IDEFoundation/IDEBreakpointBucket.h>
#import <IDEFoundation/IDEBreakpointLocation.h>
#import <IDEFoundation/IDEBreakpointManager.h>
#import <IDEFoundation/IDEBreakpointWrapper.h>
#import <IDEFoundation/IDEBuildActionEntry.h>
#import <IDEFoundation/IDEBuildArbitrator.h>
#import <IDEFoundation/IDEBuildCommandLineVerb.h>
#import <IDEFoundation/IDEBuildFolder.h>
#import <IDEFoundation/IDEBuildFolderSettings.h>
#import <IDEFoundation/IDEBuildIssueChange.h>
#import <IDEFoundation/IDEBuildIssueProvider.h>
#import <IDEFoundation/IDEBuildLogProvider.h>
#import <IDEFoundation/IDEBuildOperation.h>
#import <IDEFoundation/IDEBuildOperationDescription.h>
#import <IDEFoundation/IDEBuildOperationGroup.h>
#import <IDEFoundation/IDEBuildOperationQueueSet.h>
#import <IDEFoundation/IDEBuildOperationStatus.h>
#import <IDEFoundation/IDEBuildParameters.h>
#import <IDEFoundation/IDEBuildPlan.h>
#import <IDEFoundation/IDEBuildSchemeAction.h>
#import <IDEFoundation/IDEBuildSettingTable.h>
#import <IDEFoundation/IDEBuildSettingsProvider-Protocol.h>
#import <IDEFoundation/IDEBuildStatisticsData-Protocol.h>
#import <IDEFoundation/IDEBuildStatisticsData.h>
#import <IDEFoundation/IDEBuildStatisticsSection.h>
#import <IDEFoundation/IDEBuildTask.h>
#import <IDEFoundation/IDEBuildable-Protocol.h>
#import <IDEFoundation/IDEBuildableProduct-Protocol.h>
#import <IDEFoundation/IDEBuildableProductRunnable.h>
#import <IDEFoundation/IDEBuildableProductSupportMixIn.h>
#import <IDEFoundation/IDEBuildableSnapshot.h>
#import <IDEFoundation/IDEBuildableSupportMixIn.h>
#import <IDEFoundation/IDEBuilder.h>
#import <IDEFoundation/IDEBuilderGeneratedFileInfo.h>
#import <IDEFoundation/IDEBuilderHarvestedInfo.h>
#import <IDEFoundation/IDECertificateUtilitiesUIInitializer.h>
#import <IDEFoundation/IDEClangDiagnosticActivityLogMessage.h>
#import <IDEFoundation/IDECleanCommandLineVerb.h>
#import <IDEFoundation/IDEClientTracking-Protocol.h>
#import <IDEFoundation/IDEClientTrackingToken-Protocol.h>
#import <IDEFoundation/IDECodeModule.h>
#import <IDEFoundation/IDECommandLineArgumentEntry.h>
#import <IDEFoundation/IDECommandLineBuildLog.h>
#import <IDEFoundation/IDECommandLineBuildLogRecorder.h>
#import <IDEFoundation/IDECommandLineBuildTask.h>
#import <IDEFoundation/IDECommandLineEnvironment.h>
#import <IDEFoundation/IDECommandLineVerb.h>
#import <IDEFoundation/IDECompilationBuildTask.h>
#import <IDEFoundation/IDEConcreteClientTracker.h>
#import <IDEFoundation/IDEConcreteClientTrackingToken.h>
#import <IDEFoundation/IDEConcretePrimitiveSchemeCommand.h>
#import <IDEFoundation/IDEConcreteTestingSpecifier.h>
#import <IDEFoundation/IDEConnectionAddressXcodeServer.h>
#import <IDEFoundation/IDEConsoleAdaptor.h>
#import <IDEFoundation/IDEConsoleAdaptorDelegateProtocol-Protocol.h>
#import <IDEFoundation/IDEConsoleItem.h>
#import <IDEFoundation/IDEContainer.h>
#import <IDEFoundation/IDEContainerAbsolutePathReferenceResolutionStrategy.h>
#import <IDEFoundation/IDEContainerBuildProductsRelativeReferenceResolutionStrategy.h>
#import <IDEFoundation/IDEContainerContainerItselfReferenceResolutionStrategy.h>
#import <IDEFoundation/IDEContainerContainerRelativeReferenceResolutionStrategy.h>
#import <IDEFoundation/IDEContainerCore-Protocol.h>
#import <IDEFoundation/IDEContainerCore.h>
#import <IDEFoundation/IDEContainerCurrentSDKRelativeReferenceResolutionStrategy.h>
#import <IDEFoundation/IDEContainerDelegate-Protocol.h>
#import <IDEFoundation/IDEContainerDeveloperDirectoryRelativeReferenceResolutionStrategy.h>
#import <IDEFoundation/IDEContainerErrorPresenter-Protocol.h>
#import <IDEFoundation/IDEContainerGroupRelativeReferenceResolutionStrategy.h>
#import <IDEFoundation/IDEContainerItem.h>
#import <IDEFoundation/IDEContainerItemCore-Protocol.h>
#import <IDEFoundation/IDEContainerItemCore.h>
#import <IDEFoundation/IDEContainerItemWrapper.h>
#import <IDEFoundation/IDEContainerPathRelativeReferenceResolutionStrategy.h>
#import <IDEFoundation/IDEContainerQuery.h>
#import <IDEFoundation/IDEContainerReadOnlyItem.h>
#import <IDEFoundation/IDEContainerReadOnlyListeningItem.h>
#import <IDEFoundation/IDEContainerReferenceResolutionStrategy.h>
#import <IDEFoundation/IDEContainerReloadingDelegate-Protocol.h>
#import <IDEFoundation/IDEContainerUnlockingDelegate-Protocol.h>
#import <IDEFoundation/IDEContainerWrapper.h>
#import <IDEFoundation/IDECustomDataStoring-Protocol.h>
#import <IDEFoundation/IDECustomUpgradeTask.h>
#import <IDEFoundation/IDEDataMatrix.h>
#import <IDEFoundation/IDEDataMatrixSIn64.h>
#import <IDEFoundation/IDEDataProvider.h>
#import <IDEFoundation/IDEDataProvider_NetworkStatistics.h>
#import <IDEFoundation/IDEDataProvider_procinfo.h>
#import <IDEFoundation/IDEDebugNavigableModel-Protocol.h>
#import <IDEFoundation/IDEDebugProcess-Protocol.h>
#import <IDEFoundation/IDEDebugSession-Protocol.h>
#import <IDEFoundation/IDEDebuggerCommandBreakpointAction.h>
#import <IDEFoundation/IDEDebuggerExpression.h>
#import <IDEFoundation/IDEDebuggerSpecifier.h>
#import <IDEFoundation/IDEDebuggingAddition-Protocol.h>
#import <IDEFoundation/IDEDeferredInitialization-Protocol.h>
#import <IDEFoundation/IDEDeveloperPaths.h>
#import <IDEFoundation/IDEDeviceAppDataReference.h>
#import <IDEFoundation/IDEDeviceInstallLogProvider.h>
#import <IDEFoundation/IDEDeviceInstallWorkspaceMonitor.h>
#import <IDEFoundation/IDEDiagnosticActivityLogMessage.h>
#import <IDEFoundation/IDEDiagnosticFixItItem.h>
#import <IDEFoundation/IDEDiagnosticItemDelegate-Protocol.h>
#import <IDEFoundation/IDEDirectoryBasedCustomDataStore.h>
#import <IDEFoundation/IDEDisassemblyStorageSupport.h>
#import <IDEFoundation/IDEDistributionCodesignStep.h>
#import <IDEFoundation/IDEDistributionConsoleLogger.h>
#import <IDEFoundation/IDEDistributionCopyFileStep.h>
#import <IDEFoundation/IDEDistributionCopyInAppPurchaseContentStep.h>
#import <IDEFoundation/IDEDistributionCopyItemStep.h>
#import <IDEFoundation/IDEDistributionCopySwiftSupportStep.h>
#import <IDEFoundation/IDEDistributionCreateDestRootStep.h>
#import <IDEFoundation/IDEDistributionCreateIPAStep.h>
#import <IDEFoundation/IDEDistributionCreatePKGStep.h>
#import <IDEFoundation/IDEDistributionCreatePackageStep.h>
#import <IDEFoundation/IDEDistributionEmbedProfileStep.h>
#import <IDEFoundation/IDEDistributionFileLogger.h>
#import <IDEFoundation/IDEDistributionIssue.h>
#import <IDEFoundation/IDEDistributionItem.h>
#import <IDEFoundation/IDEDistributionItemProcessingResults.h>
#import <IDEFoundation/IDEDistributionItemSigningInfo.h>
#import <IDEFoundation/IDEDistributionLogging.h>
#import <IDEFoundation/IDEDistributionMethod.h>
#import <IDEFoundation/IDEDistributionMethodAppStore.h>
#import <IDEFoundation/IDEDistributionMethodExport.h>
#import <IDEFoundation/IDEDistributionMethodExportArchive.h>
#import <IDEFoundation/IDEDistributionMethodInAppPurchaseContent.h>
#import <IDEFoundation/IDEDistributionMethodInAppPurchaseContentPackage.h>
#import <IDEFoundation/IDEDistributionMethodInAppPurchaseContentSubmit.h>
#import <IDEFoundation/IDEDistributionMethodInAppPurchaseContentValidate.h>
#import <IDEFoundation/IDEDistributionMethodManager.h>
#import <IDEFoundation/IDEDistributionMethodSaveBuiltProducts.h>
#import <IDEFoundation/IDEDistributionProcessingPipeline.h>
#import <IDEFoundation/IDEDistributionProcessingPipelineContext-Protocol.h>
#import <IDEFoundation/IDEDistributionProcessingStep.h>
#import <IDEFoundation/IDEDistributionProvisioning.h>
#import <IDEFoundation/IDEDistributionProvisioningSnapshot.h>
#import <IDEFoundation/IDEDistributionSymbolsStep.h>
#import <IDEFoundation/IDEDocumentIssueSummary.h>
#import <IDEFoundation/IDEEnergyAddition.h>
#import <IDEFoundation/IDEEnergyLogScoreFormatter.h>
#import <IDEFoundation/IDEEntitlementsDictionary.h>
#import <IDEFoundation/IDEEntitlementsProcessor.h>
#import <IDEFoundation/IDEEntitlementsWhiteOutMarker.h>
#import <IDEFoundation/IDEEntityIdentifier.h>
#import <IDEFoundation/IDEEnvironmentVariableEntry.h>
#import <IDEFoundation/IDEExceptionBreakpoint.h>
#import <IDEFoundation/IDEExecutingOperationTrackable-Protocol.h>
#import <IDEFoundation/IDEExecutionAction.h>
#import <IDEFoundation/IDEExecutionActionArchivingProxy.h>
#import <IDEFoundation/IDEExecutionActionOperation.h>
#import <IDEFoundation/IDEExecutionActionType.h>
#import <IDEFoundation/IDEExecutionEnvironment.h>
#import <IDEFoundation/IDEExecutionOperationTracker.h>
#import <IDEFoundation/IDEExecutionRunnableTracker.h>
#import <IDEFoundation/IDEExecutionTracker.h>
#import <IDEFoundation/IDEExtendedPlatformInfo.h>
#import <IDEFoundation/IDEFileBreakpoint.h>
#import <IDEFoundation/IDEFileBreakpointWrapper.h>
#import <IDEFoundation/IDEFileBuildOperation.h>
#import <IDEFoundation/IDEFileReference.h>
#import <IDEFoundation/IDEFileReferenceContainerObserver.h>
#import <IDEFoundation/IDEFileReferenceContainerObserverCacheKey.h>
#import <IDEFoundation/IDEFileReferenceCore-Protocol.h>
#import <IDEFoundation/IDEFileReferenceCore.h>
#import <IDEFoundation/IDEFileReferenceWrapper.h>
#import <IDEFoundation/IDEFindCommandLineVerb.h>
#import <IDEFoundation/IDEFolder.h>
#import <IDEFoundation/IDEFolderCore-Protocol.h>
#import <IDEFoundation/IDEFolderCore.h>
#import <IDEFoundation/IDEFoundationTestInitializer.h>
#import <IDEFoundation/IDEFramework.h>
#import <IDEFoundation/IDEFrameworkCore-Protocol.h>
#import <IDEFoundation/IDEFrameworkCore.h>
#import <IDEFoundation/IDEGaugeDataProviderService.h>
#import <IDEFoundation/IDEGaugeDataQuery.h>
#import <IDEFoundation/IDEGaugeDataQueryCoordinator.h>
#import <IDEFoundation/IDEGroup.h>
#import <IDEFoundation/IDEGroupCore-Protocol.h>
#import <IDEFoundation/IDEGroupCore.h>
#import <IDEFoundation/IDEGroupWrapper.h>
#import <IDEFoundation/IDEHelpCommandLineVerb.h>
#import <IDEFoundation/IDEInMemoryActivityLogRecord.h>
#import <IDEFoundation/IDEInMemoryLogStore.h>
#import <IDEFoundation/IDEInMemoryLogStore_Impl.h>
#import <IDEFoundation/IDEIndex.h>
#import <IDEFoundation/IDEIndexAutoImportItem.h>
#import <IDEFoundation/IDEIndexAutoImportItemCollection.h>
#import <IDEFoundation/IDEIndexCallableSymbol.h>
#import <IDEFoundation/IDEIndexCategorySymbol.h>
#import <IDEFoundation/IDEIndexClangDataSource.h>
#import <IDEFoundation/IDEIndexClangQueryProvider.h>
#import <IDEFoundation/IDEIndexClangTranslationUnit.h>
#import <IDEFoundation/IDEIndexClassSymbol.h>
#import <IDEFoundation/IDEIndexCodeCompletionContext.h>
#import <IDEFoundation/IDEIndexCollection.h>
#import <IDEFoundation/IDEIndexCompletionArray.h>
#import <IDEFoundation/IDEIndexCompletionItem.h>
#import <IDEFoundation/IDEIndexContainerSymbol.h>
#import <IDEFoundation/IDEIndexDBConnection.h>
#import <IDEFoundation/IDEIndexDBFactory.h>
#import <IDEFoundation/IDEIndexDBSQLStream.h>
#import <IDEFoundation/IDEIndexDBStringStorage.h>
#import <IDEFoundation/IDEIndexDBTempTable.h>
#import <IDEFoundation/IDEIndexDBTransaction.h>
#import <IDEFoundation/IDEIndexDataSource.h>
#import <IDEFoundation/IDEIndexDatabase.h>
#import <IDEFoundation/IDEIndexDatabaseDelegate-Protocol.h>
#import <IDEFoundation/IDEIndexDatabaseQueryProvider.h>
#import <IDEFoundation/IDEIndexFileCollection.h>
#import <IDEFoundation/IDEIndexGenericQueryProvider.h>
#import <IDEFoundation/IDEIndexGenericSymbolFormatter.h>
#import <IDEFoundation/IDEIndexImportSession.h>
#import <IDEFoundation/IDEIndexImporter.h>
#import <IDEFoundation/IDEIndexModulesIndexable.h>
#import <IDEFoundation/IDEIndexNewFile.h>
#import <IDEFoundation/IDEIndexNewFileBase-Protocol.h>
#import <IDEFoundation/IDEIndexNewMainFile.h>
#import <IDEFoundation/IDEIndexNewSymbol.h>
#import <IDEFoundation/IDEIndexProductInfo.h>
#import <IDEFoundation/IDEIndexPropertySymbol.h>
#import <IDEFoundation/IDEIndexProtocolSymbol.h>
#import <IDEFoundation/IDEIndexQPManager.h>
#import <IDEFoundation/IDEIndexQueryProvider-Protocol.h>
#import <IDEFoundation/IDEIndexScannerDataSource.h>
#import <IDEFoundation/IDEIndexSymbol.h>
#import <IDEFoundation/IDEIndexSymbolCollection.h>
#import <IDEFoundation/IDEIndexSymbolFormatter-Protocol.h>
#import <IDEFoundation/IDEIndexSymbolFormatterFactory.h>
#import <IDEFoundation/IDEIndexSymbolOccurrence.h>
#import <IDEFoundation/IDEIndexSymbolOccurrenceCollection.h>
#import <IDEFoundation/IDEIndexSymbolOccurrenceWithSymbolCollection.h>
#import <IDEFoundation/IDEIndexSymbolWithDefiningOccurrenceCollection.h>
#import <IDEFoundation/IDEIndexSymbolWithModelOccurrenceCollection.h>
#import <IDEFoundation/IDEIndexSymbolWithOccurrenceCollection.h>
#import <IDEFoundation/IDEIndexTestMethodCollection.h>
#import <IDEFoundation/IDEIndexTestPlistDataSource.h>
#import <IDEFoundation/IDEIndexUniqueStringMap.h>
#import <IDEFoundation/IDEIndexUnknownDataSource.h>
#import <IDEFoundation/IDEIndexable-Protocol.h>
#import <IDEFoundation/IDEIndexableMainThreadProxy.h>
#import <IDEFoundation/IDEIndexableProvider-Protocol.h>
#import <IDEFoundation/IDEIndexingEngine.h>
#import <IDEFoundation/IDEIndexingJob.h>
#import <IDEFoundation/IDEIndexingJobScheduler.h>
#import <IDEFoundation/IDEIndexingPrebuildController.h>
#import <IDEFoundation/IDEInitialization-Protocol.h>
#import <IDEFoundation/IDEInitializationErrorRecoveryAttempter.h>
#import <IDEFoundation/IDEInstallCommandLineVerb.h>
#import <IDEFoundation/IDEInstallLocalMacService.h>
#import <IDEFoundation/IDEInstallLocalMacWorker.h>
#import <IDEFoundation/IDEInstallSchemeAction.h>
#import <IDEFoundation/IDEIntegrateSchemeAction.h>
#import <IDEFoundation/IDEIntegrityLogDataSource-Protocol.h>
#import <IDEFoundation/IDEInternalBreakpointDelegate-Protocol.h>
#import <IDEFoundation/IDEIssue.h>
#import <IDEFoundation/IDEIssueFileGroup.h>
#import <IDEFoundation/IDEIssueGroup.h>
#import <IDEFoundation/IDEIssueLogRecordsGroup.h>
#import <IDEFoundation/IDEIssueManager.h>
#import <IDEFoundation/IDEIssueManager_ByFileObserverToken.h>
#import <IDEFoundation/IDEIssueProvider.h>
#import <IDEFoundation/IDEIssueProviderSession.h>
#import <IDEFoundation/IDEIssueTypeGroup.h>
#import <IDEFoundation/IDEItemReferenceWrapper.h>
#import <IDEFoundation/IDELaunchParametersSnapshot.h>
#import <IDEFoundation/IDELaunchRunPhasePathEntry.h>
#import <IDEFoundation/IDELaunchSchemeAction.h>
#import <IDEFoundation/IDELaunchSession.h>
#import <IDEFoundation/IDELocalizationBundleExportContext.h>
#import <IDEFoundation/IDELocalizationExporter.h>
#import <IDEFoundation/IDELocalizationImporter.h>
#import <IDEFoundation/IDELocalizationImporterContext.h>
#import <IDEFoundation/IDELocalizationLanguageExportContext.h>
#import <IDEFoundation/IDELocalizationLanguageImportContext.h>
#import <IDEFoundation/IDELocalizationManager.h>
#import <IDEFoundation/IDELocalizationManagerContext.h>
#import <IDEFoundation/IDELocalizationStream.h>
#import <IDEFoundation/IDELocalizationStreamConsumer-Protocol.h>
#import <IDEFoundation/IDELocalizationStreamPublisher-Protocol.h>
#import <IDEFoundation/IDELocalizationWork.h>
#import <IDEFoundation/IDELocalizationWorkContext.h>
#import <IDEFoundation/IDELocalizationWorkProgress-Protocol.h>
#import <IDEFoundation/IDELocalizationWorkReadStrings-Protocol.h>
#import <IDEFoundation/IDELocalizationWorkSystemTask-Protocol.h>
#import <IDEFoundation/IDELocalizationWorkWriteData-Protocol.h>
#import <IDEFoundation/IDELocalizationWorkWriteStrings-Protocol.h>
#import <IDEFoundation/IDELocalizationXLIFFComparisonContext.h>
#import <IDEFoundation/IDELocalizationXLIFFComparisonFile.h>
#import <IDEFoundation/IDELocalizationXLIFFComparisonIssue.h>
#import <IDEFoundation/IDELocalizationXLIFFComparisonIssueLocation.h>
#import <IDEFoundation/IDELocalizationXLIFFTextualRepresentation.h>
#import <IDEFoundation/IDELocalizedGroup-Protocol.h>
#import <IDEFoundation/IDELocalizedPlistAdaptor.h>
#import <IDEFoundation/IDELocalizedResourceAdaptor.h>
#import <IDEFoundation/IDELocalizedResourceAdaptorWorkContext.h>
#import <IDEFoundation/IDELocalizedResourcePopulationContext.h>
#import <IDEFoundation/IDELocalizedStringsAdaptor.h>
#import <IDEFoundation/IDELocation.h>
#import <IDEFoundation/IDELocationScenario.h>
#import <IDEFoundation/IDELocationScenarioReference.h>
#import <IDEFoundation/IDELocationSimulator.h>
#import <IDEFoundation/IDELogDocumentLocation.h>
#import <IDEFoundation/IDELogManager.h>
#import <IDEFoundation/IDELogProvider.h>
#import <IDEFoundation/IDELogStore.h>
#import <IDEFoundation/IDEMasterPtyFileHandle.h>
#import <IDEFoundation/IDEMutableBuildParameters.h>
#import <IDEFoundation/IDEMutableOverridingBuildProperties.h>
#import <IDEFoundation/IDENetServiceXcodeServer.h>
#import <IDEFoundation/IDENotifyingLocalizedGroup.h>
#import <IDEFoundation/IDEOCUnitTestOutputParser.h>
#import <IDEFoundation/IDEOCUnitTestOutputParserDelegate-Protocol.h>
#import <IDEFoundation/IDEOCUnitTestRunner.h>
#import <IDEFoundation/IDEOCUnitTestRunnerOperation.h>
#import <IDEFoundation/IDEOnDiskActivityLogRecord.h>
#import <IDEFoundation/IDEOnDiskLogStore.h>
#import <IDEFoundation/IDEOnDiskLogStore_Impl.h>
#import <IDEFoundation/IDEOverridingBuildProperties.h>
#import <IDEFoundation/IDEPathRunnable.h>
#import <IDEFoundation/IDEPosixSpawnLaunchLocalService.h>
#import <IDEFoundation/IDEPosixSpawnLauncher.h>
#import <IDEFoundation/IDEPosixSpawnLocalService.h>
#import <IDEFoundation/IDEPrimitiveSchemeCommand-Protocol.h>
#import <IDEFoundation/IDEProductType.h>
#import <IDEFoundation/IDEProductTypeProvider-Protocol.h>
#import <IDEFoundation/IDEProfileOperation.h>
#import <IDEFoundation/IDEProfileSchemeAction.h>
#import <IDEFoundation/IDEPseudoTerminal.h>
#import <IDEFoundation/IDEQueuedOperationInfo.h>
#import <IDEFoundation/IDEReadOnlyItem-Protocol.h>
#import <IDEFoundation/IDEReadOnlyItemsManager.h>
#import <IDEFoundation/IDERefactoring.h>
#import <IDEFoundation/IDERefactoringBuildSettings.h>
#import <IDEFoundation/IDERefactoringKeyValueAccessorMethodDescriptor.h>
#import <IDEFoundation/IDERemoteRunnable.h>
#import <IDEFoundation/IDERenameableXcode3ProjectItem.h>
#import <IDEFoundation/IDERunContextManager.h>
#import <IDEFoundation/IDERunDestination.h>
#import <IDEFoundation/IDERunDestinationFallbackSelector.h>
#import <IDEFoundation/IDERunDestinationFallbackSelectorDeviceInfo-Protocol.h>
#import <IDEFoundation/IDERunDestinationManager.h>
#import <IDEFoundation/IDERunDestinationSelectable.h>
#import <IDEFoundation/IDERunDeviceService.h>
#import <IDEFoundation/IDERunGeneratesOutputAlertEvent.h>
#import <IDEFoundation/IDERunOperation.h>
#import <IDEFoundation/IDERunOperationPathWorker.h>
#import <IDEFoundation/IDERunOperationWorker.h>
#import <IDEFoundation/IDERunOperationWorkerDelegate-Protocol.h>
#import <IDEFoundation/IDERunOperationWorkerGroup.h>
#import <IDEFoundation/IDERunOperationWorkerTracker-Protocol.h>
#import <IDEFoundation/IDERunnable.h>
#import <IDEFoundation/IDESDKInfoCommandLineVerb.h>
#import <IDEFoundation/IDEScheme.h>
#import <IDEFoundation/IDESchemeAction.h>
#import <IDEFoundation/IDESchemeActionAbstractTestSummaryObject.h>
#import <IDEFoundation/IDESchemeActionDeviceRecord.h>
#import <IDEFoundation/IDESchemeActionDummyTestSummary.h>
#import <IDEFoundation/IDESchemeActionIssueSummary.h>
#import <IDEFoundation/IDESchemeActionPlatformRecord.h>
#import <IDEFoundation/IDESchemeActionRecord.h>
#import <IDEFoundation/IDESchemeActionResult.h>
#import <IDEFoundation/IDESchemeActionResultOperation.h>
#import <IDEFoundation/IDESchemeActionRunDestinationRecord.h>
#import <IDEFoundation/IDESchemeActionSDKRecord.h>
#import <IDEFoundation/IDESchemeActionTestFailureIssueSummary.h>
#import <IDEFoundation/IDESchemeActionTestFailureSummary.h>
#import <IDEFoundation/IDESchemeActionTestPerformanceMetricSummary.h>
#import <IDEFoundation/IDESchemeActionTestSummary.h>
#import <IDEFoundation/IDESchemeActionTestSummaryContainer-Protocol.h>
#import <IDEFoundation/IDESchemeActionTestSummaryGroup.h>
#import <IDEFoundation/IDESchemeActionTestableSummary.h>
#import <IDEFoundation/IDESchemeActionsInvocationRecord.h>
#import <IDEFoundation/IDESchemeActionsInvocationRecordUpdateDelegate-Protocol.h>
#import <IDEFoundation/IDESchemeBasedCommandLineVerb.h>
#import <IDEFoundation/IDESchemeBuildableReference.h>
#import <IDEFoundation/IDESchemeCommand.h>
#import <IDEFoundation/IDESchemeOptionReference.h>
#import <IDEFoundation/IDEScriptingElement.h>
#import <IDEFoundation/IDEScriptingProxy.h>
#import <IDEFoundation/IDEScriptingWrapper.h>
#import <IDEFoundation/IDEShellCommandBreakpointAction.h>
#import <IDEFoundation/IDEShellXPCDebugSession.h>
#import <IDEFoundation/IDEShellXPCProcess.h>
#import <IDEFoundation/IDESimulateLocationService.h>
#import <IDEFoundation/IDESnapshotConfirmationDelegate-Protocol.h>
#import <IDEFoundation/IDESnapshotItem.h>
#import <IDEFoundation/IDESnapshotsEngine.h>
#import <IDEFoundation/IDESnapshotsManager.h>
#import <IDEFoundation/IDESnapshotsRestoreContext.h>
#import <IDEFoundation/IDESourceControlArchiveWrapper.h>
#import <IDEFoundation/IDESourceControlBranch.h>
#import <IDEFoundation/IDESourceControlCredentialsValidator.h>
#import <IDEFoundation/IDESourceControlDocumentLocation.h>
#import <IDEFoundation/IDESourceControlDummyItem.h>
#import <IDEFoundation/IDESourceControlExtension.h>
#import <IDEFoundation/IDESourceControlIssueProvider.h>
#import <IDEFoundation/IDESourceControlLogProvider.h>
#import <IDEFoundation/IDESourceControlManager.h>
#import <IDEFoundation/IDESourceControlMultipleStepInvalidationToken.h>
#import <IDEFoundation/IDESourceControlOperation.h>
#import <IDEFoundation/IDESourceControlPatch.h>
#import <IDEFoundation/IDESourceControlPatchBuilder.h>
#import <IDEFoundation/IDESourceControlPatchItemNode.h>
#import <IDEFoundation/IDESourceControlPatchManager.h>
#import <IDEFoundation/IDESourceControlPatchNode-Protocol.h>
#import <IDEFoundation/IDESourceControlPatchWorkingTreeNode.h>
#import <IDEFoundation/IDESourceControlProject.h>
#import <IDEFoundation/IDESourceControlRepository.h>
#import <IDEFoundation/IDESourceControlRequest.h>
#import <IDEFoundation/IDESourceControlRevision.h>
#import <IDEFoundation/IDESourceControlRevisionWrapper.h>
#import <IDEFoundation/IDESourceControlTaskOperation.h>
#import <IDEFoundation/IDESourceControlTree.h>
#import <IDEFoundation/IDESourceControlTreeGroup.h>
#import <IDEFoundation/IDESourceControlTreeItem.h>
#import <IDEFoundation/IDESourceControlWorkingCopyConfiguration.h>
#import <IDEFoundation/IDESourceControlWorkingTree.h>
#import <IDEFoundation/IDESourceControlWorkingTreeGroup.h>
#import <IDEFoundation/IDESourceControlWorkingTreeItem.h>
#import <IDEFoundation/IDESourceControlWorkingTreeItemHolder.h>
#import <IDEFoundation/IDESourceControlWorkspaceMonitor.h>
#import <IDEFoundation/IDESourceTreeProvider-Protocol.h>
#import <IDEFoundation/IDESourceTrees.h>
#import <IDEFoundation/IDEStandardTestRunner.h>
#import <IDEFoundation/IDEStandardTestable.h>
#import <IDEFoundation/IDEStructureEditing-Protocol.h>
#import <IDEFoundation/IDESymbolicBreakpoint.h>
#import <IDEFoundation/IDESymbolicBreakpointWrapper.h>
#import <IDEFoundation/IDESyntheticLaunchSession.h>
#import <IDEFoundation/IDETest.h>
#import <IDEFoundation/IDETestBaselineRecord.h>
#import <IDEFoundation/IDETestBlueprintHostSettings.h>
#import <IDEFoundation/IDETestBundleBaselineRecord.h>
#import <IDEFoundation/IDETestBundleDeviceRecord.h>
#import <IDEFoundation/IDETestBundleRunDestinationRecord.h>
#import <IDEFoundation/IDETestContainer-Protocol.h>
#import <IDEFoundation/IDETestFailureBreakpoint.h>
#import <IDEFoundation/IDETestIdentifierResolver.h>
#import <IDEFoundation/IDETestIssue.h>
#import <IDEFoundation/IDETestManager.h>
#import <IDEFoundation/IDETestObserver-Protocol.h>
#import <IDEFoundation/IDETestPerformanceMetricBaselineRecord.h>
#import <IDEFoundation/IDETestProgressNotificationsObserver.h>
#import <IDEFoundation/IDETestReportDocumentLocation.h>
#import <IDEFoundation/IDETestResult.h>
#import <IDEFoundation/IDETestResultMessage.h>
#import <IDEFoundation/IDETestRunSession.h>
#import <IDEFoundation/IDETestRunner.h>
#import <IDEFoundation/IDETestSchemeAction.h>
#import <IDEFoundation/IDETestSchemeBaselineRecord.h>
#import <IDEFoundation/IDETestable-Protocol.h>
#import <IDEFoundation/IDETestableIssueProvider.h>
#import <IDEFoundation/IDETestableProvider-Protocol.h>
#import <IDEFoundation/IDETestableReference.h>
#import <IDEFoundation/IDETestableReferenceTestIdentifier.h>
#import <IDEFoundation/IDETestingSpecification.h>
#import <IDEFoundation/IDETestingSpecifier-Protocol.h>
#import <IDEFoundation/IDETestingSystem.h>
#import <IDEFoundation/IDETestsInTestableObserver-Protocol.h>
#import <IDEFoundation/IDETextIndex.h>
#import <IDEFoundation/IDETextIndexDataProvider.h>
#import <IDEFoundation/IDETextIndexPropertyListDataProvider.h>
#import <IDEFoundation/IDETextIndexRTFDataProvider.h>
#import <IDEFoundation/IDETextIndexTextDataProvider.h>
#import <IDEFoundation/IDETextIndexTextFindableWrapper.h>
#import <IDEFoundation/IDETypeIdentifier.h>
#import <IDEFoundation/IDEUIATestHostTask.h>
#import <IDEFoundation/IDEUIATestRunner.h>
#import <IDEFoundation/IDEUIATestScriptAgentCommunicator.h>
#import <IDEFoundation/IDEUnitTestContainerUnlockingDelegate.h>
#import <IDEFoundation/IDEUnitTestLogProvider.h>
#import <IDEFoundation/IDEUnitTestsActivityLogBuilder.h>
#import <IDEFoundation/IDEUnitTestsObserver-Protocol.h>
#import <IDEFoundation/IDEUnitTestsOperationsObserver.h>
#import <IDEFoundation/IDEUnitTestsRunnerAdaptor.h>
#import <IDEFoundation/IDEUnitTestsSummariesBuilder.h>
#import <IDEFoundation/IDEUpgradeBlueprintContext.h>
#import <IDEFoundation/IDEUpgradeContainerContext.h>
#import <IDEFoundation/IDEUpgradeContext.h>
#import <IDEFoundation/IDEUpgradeSchemeContext.h>
#import <IDEFoundation/IDEUpgradeTask.h>
#import <IDEFoundation/IDEUpgradeableItem-Protocol.h>
#import <IDEFoundation/IDEVersionCommandLineVerb.h>
#import <IDEFoundation/IDEVersionedFileManager.h>
#import <IDEFoundation/IDEWatchpoint.h>
#import <IDEFoundation/IDEWatchpointNotificationInfo.h>
#import <IDEFoundation/IDEWorkspace.h>
#import <IDEFoundation/IDEWorkspaceArena.h>
#import <IDEFoundation/IDEWorkspaceArenaInfo.h>
#import <IDEFoundation/IDEWorkspaceArenaSnapshot.h>
#import <IDEFoundation/IDEWorkspaceBasedCommandLineVerb.h>
#import <IDEFoundation/IDEWorkspaceCore.h>
#import <IDEFoundation/IDEWorkspaceDelegate-Protocol.h>
#import <IDEFoundation/IDEWorkspaceInfoCommandLineVerb.h>
#import <IDEFoundation/IDEWorkspaceIntegrityIssueProvider.h>
#import <IDEFoundation/IDEWorkspaceIntegrityIssueProviderContext.h>
#import <IDEFoundation/IDEWorkspaceReferencedTestablesObserver-Protocol.h>
#import <IDEFoundation/IDEWorkspaceSettings.h>
#import <IDEFoundation/IDEWorkspaceSharedSettings.h>
#import <IDEFoundation/IDEWorkspaceSnapshotManager.h>
#import <IDEFoundation/IDEWorkspaceUpgradeTasksController.h>
#import <IDEFoundation/IDEWorkspaceUserSettings.h>
#import <IDEFoundation/IDEWorkspaceWrappingContainer-Protocol.h>
#import <IDEFoundation/IDEXMLPackageContainer.h>
#import <IDEFoundation/IDEXMLPackageContainerCore-Protocol.h>
#import <IDEFoundation/IDEXMLPackageContainerCore.h>
#import <IDEFoundation/IDEXcodeServer.h>
#import <IDEFoundation/IDEXcodeServerManager.h>
#import <IDEFoundation/IDEXcodeServerUseConfiguration.h>
#import <IDEFoundation/IDEiCloudEntitlementsProcessor.h>
#import <IDEFoundation/NSArray-IDELocalizationStreamArrayUtilities.h>
#import <IDEFoundation/NSCoding-Protocol.h>
#import <IDEFoundation/NSCopying-Protocol.h>
#import <IDEFoundation/NSError-DVTDeviceIneligibility.h>
#import <IDEFoundation/NSFastEnumeration-Protocol.h>
#import <IDEFoundation/NSFileManager-IDESourceControlUtilities.h>
#import <IDEFoundation/NSLocale-IDELocDisplayName.h>
#import <IDEFoundation/NSLocale-IDELoc_IPPrivateMethods.h>
#import <IDEFoundation/NSMutableCopying-Protocol.h>
#import <IDEFoundation/NSNumber-IDESourceControlAdditions.h>
#import <IDEFoundation/NSObject-IDEModelObjectTypeIdentification.h>
#import <IDEFoundation/NSSecureCoding-Protocol.h>
#import <IDEFoundation/NSString-IDEIndexAdditions.h>
#import <IDEFoundation/NSURLConnectionDelegate-Protocol.h>
#import <IDEFoundation/ProjectItemWrapper.h>
#import <IDEFoundation/UIAInstrumentAuthorizedAPI-Protocol.h>
#import <IDEFoundation/XCTestDriverInterface-Protocol.h>
#import <IDEFoundation/XCTestManager_DaemonConnectionInterface-Protocol.h>
#import <IDEFoundation/XCTestManager_IDEInterface-Protocol.h>
#import <IDEFoundation/_IDEDeferredInitializationInvocation.h>
#import <IDEFoundation/_IDEFolderRootGroup.h>
#import <IDEFoundation/_IDEFoundationPrivateClassForFindingBundle.h>
#import <IDEFoundation/_IDEIssueProvisionInfo.h>
#import <IDEFoundation/_IDELegacyUserDefaultsImporter.h>
#import <IDEFoundation/_IDELocalizationAddFileReferenceContext.h>
#import <IDEFoundation/_IDELocalizationExporterConfig.h>
#import <IDEFoundation/_IDELocalizationStreamBlockBased.h>
#import <IDEFoundation/_IDELocalizationStreamConcat.h>
#import <IDEFoundation/_IDELocalizationStreamJoin.h>
#import <IDEFoundation/_IDELocalizationStreamMap.h>
#import <IDEFoundation/_IDELocalizationStreamReturn.h>
#import <IDEFoundation/_IDELocalizationStreamThrow.h>
#import <IDEFoundation/_IDELocalizationWriteStringsContext.h>
#import <IDEFoundation/_IDELocalizedPlistAdaptorReadContext.h>
#import <IDEFoundation/_IDELocalizedPlistAdaptorWriteContext.h>
#import <IDEFoundation/_IDELocalizedStringsAdaptorReadContext.h>
#import <IDEFoundation/_IDELocalizedStringsAdaptorWriteContext.h>
#import <IDEFoundation/_IDEOCUnitTestRecord.h>
#import <IDEFoundation/_IDETestFileChangeBroker.h>
#import <IDEFoundation/_IDETestManagerAPIMediator.h>
#import <IDEFoundation/_IDETestResultsProcessor.h>
#import <IDEFoundation/_IDETestResultsProcessorDelegate-Protocol.h>
#import <IDEFoundation/_IDETestRunPerTestableSessionState.h>
#import <IDEFoundation/_IDETestableState.h>
#import <IDEFoundation/_IDEUnitTestParserMediator.h>
#import <IDEFoundation/_IDEUnitTestParserValidator.h>
